steps:
  # Build the container image
  - id: 'build image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
      - '${_SERVICE_FOLDER}'
  # Push the container image to Container Registry
  - id: 'push image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
  # Deploy container image to Cloud Run
  - id: 'deploy image'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
      - '--allow-unauthenticated'
      - '--region'
      - 'us-east1'
      - '--memory'
      - '128Mi'
      - '--timeout'
      - '1800'

substitutions:
  _SERVICE_FOLDER: .
  _IMAGE_NAME: test-service
  _SERVICE_NAME: test-service

images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
